## Day 3
### Numpy

In [1]:
kanto=[73,67,43]
johto=[91,88,64]
hoenn=[87,134,58]
sinnoh=[102,43,37]
unova=[69,96,70]

In [2]:
weights=[0.3,0.2,0.5]

In [3]:
for item in zip(kanto,weights):
    print(item)

(73, 0.3)
(67, 0.2)
(43, 0.5)


In [4]:
def crop_yield(region,weights):
    result=0
    for x,w in zip(region,weights):
        result+=x*w
    return result

In [5]:
crop_yield(kanto,weights)

56.8

In [6]:
!pip install numpy --upgrade --quiet

In [7]:
import numpy as np

In [8]:
kanto=np.array([73,67,43])

In [9]:
kanto

array([73, 67, 43])

In [10]:
weights=np.array([0.3,0.2,0.5])

In [11]:
weights

array([0.3, 0.2, 0.5])

In [12]:
type(kanto)

numpy.ndarray

In [13]:
np.dot(kanto,weights)

56.8

In [14]:
kanto.sum()     # sum of all the elements of kanto

183

In [15]:
climate_data=np.array([[73,67,43],
                      [91,88,64],
                      [87,134,58],
                      [102,43,37],
                      [69,96,70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [16]:
climate_data.shape

(5, 3)

In [18]:
weights.dtype

dtype('float64')

In [19]:
climate_data.dtype

dtype('int32')

In [20]:
np.matmul(climate_data,weights)                 #matrix multiplication

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [21]:
climate_data@weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [22]:
import urllib.request

urllib.request.urlretrieve(
        'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0xafdc448>)

In [23]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [24]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [25]:
climate_data.shape

(10000, 3)

In [26]:
yields=climate_data@weights

In [28]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [29]:
climate_results=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [30]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [34]:
np.savetxt('climate_result.txt',climate_results,header='temp,rainfall,humidity,yeilds',fmt='%.2f')

In [37]:
sum_yields=np.sum(yields)
sum_yields

600405.8


np.sum  np.exp  np.round  

np.reshape  np.stack  np.concatenate   np.split

np.matmul  np.dot  np.transpose np.eigvalues

np.mean  np.median  np.std  np.max


In [43]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [19, 1, 2, 3]])

In [44]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [45]:
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [38, 12, 14, 16]])

In [46]:
arr2==arr3

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [49]:
arr2<arr3

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [50]:
(arr2==arr3).sum()

1

In [51]:
arr1 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [54]:
arr1.shape

(3, 2, 4)

In [58]:
arr1[1,1,0]

63.0

In [59]:
arr1[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [60]:
arr1[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [61]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [66]:
np.random.rand(5)

array([0.82067885, 0.32252538, 0.21118378, 0.17936322, 0.60243262])

In [67]:
np.random.randn(2, 3) 

array([[-0.27426698, -0.48935462,  1.4248135 ],
       [ 0.57722306,  1.86790656, -0.02983112]])

In [68]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [69]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [70]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 